/**
 * Maps an application route (pathname) to a manual section id.
 * Order matters: more specific routes must come first.
 * Section ids are generated by parseManual.ts using "<number>-<slug>".
 */
const RAW_MAP: Array<[RegExp, string]> = [
  // Auth
  [/^\/auth$/, "2-authentification-securite"],
  [/^\/reset-password/, "2-3-reinitialisation-du-mot-de-passe"],

  // GMAO
  [/^\/$/, "3-1-dashboard"],
  [/^\/machines\/new/, "3-2-machines"],
  [/^\/machines\/[^/]+\/edit/, "3-2-machines"],
  [/^\/machines\/[^/]+/, "3-2-machines"],
  [/^\/machines/, "3-2-machines"],
  [/^\/equipements/, "3-3-equipements"],
  [/^\/organes/, "3-3-equipements"],
  [/^\/lignes/, "3-4-lignes-de-production"],
  [/^\/pdr/, "3-5-pieces-de-rechange-pdr"],
  [/^\/tickets/, "3-6-tickets-de-maintenance"],
  [/^\/preventif/, "3-7-maintenance-preventive"],
  [/^\/maintenance\/shift/, "3-8-shift-maintenance"],
  [/^\/maintenance\/journal/, "3-9-journal-des-interventions"],
  [/^\/maintenance\/historique/, "3-9-journal-des-interventions"],
  [/^\/analytics/, "3-10-analyse-kpi"],

  // GPAO
  [/^\/gpao\/of/, "4-2-ordres-de-fabrication-of"],
  [/^\/gpao\/produits/, "4-3-produits"],
  [/^\/gpao\/articles/, "4-4-articles-matieres-premieres"],
  [/^\/gpao\/recettes/, "4-5-recettes-unifiees-avec-la-nomenclature-bom-qualite"],
  [/^\/gpao\/shift/, "4-6-shift-production"],
  [/^\/gpao\/consommations/, "4-7-consommations"],
  [/^\/gpao\/arrets/, "4-8-arrets"],
  [/^\/gpao$/, "4-1-dashboard-production"],

  // Qualité
  [/^\/qualite\/shift/, "4-9-module-qualite"],
  [/^\/qualite/, "4-9-module-qualite"],

  // Paramètres
  [/^\/parametres\/users/, "6-1-securite-acces"],
  [/^\/parametres\/familles-produits/, "6-2-referentiels-classification"],
  [/^\/parametres\/familles-pdr/, "6-2-referentiels-classification"],
  [/^\/parametres\/familles/, "6-2-referentiels-classification"],
  [/^\/parametres\/pannes/, "6-2-referentiels-classification"],
  [/^\/parametres\/document-categories/, "6-2-referentiels-classification"],
  [/^\/parametres\/document-permissions/, "7-documents"],
  [/^\/parametres\/lignes/, "6-3-production-organisation"],
  [/^\/parametres\/rotations/, "6-6-rotations-systemes-de-shift"],
  [/^\/parametres\/shifts/, "6-3-production-organisation"],
  [/^\/parametres\/images/, "6-4-configuration-generale"],
  [/^\/parametres\/general/, "6-4-configuration-generale"],
  [/^\/parametres\/scan-history/, "6-4-configuration-generale"],
  [/^\/parametres\/smtp/, "6-bis-2-configuration-smtp-parametres-smtp"],
  [/^\/parametres\/notifications/, "6-bis-3-regles-de-notification-parametres-notifications"],
  [/^\/parametres\/validations/, "9-roles-permissions"],
  [/^\/parametres\/roles/, "9-roles-permissions"],
  [/^\/parametres\/pdr-stock-permissions/, "9-5-permissions-stock-pdr-speciales"],
  [/^\/parametres\/qualite/, "6-5-parametrage-qualite"],
  [/^\/parametres/, "6-administration-parametres"],

  // Audit / notifs / validations / securité
  [/^\/securite/, "6-1-securite-acces"],
  [/^\/audit/, "6-administration-parametres"],
  [/^\/notifications/, "6-bis-notifications-emails"],
  [/^\/validations/, "9-roles-permissions"],
  [/^\/recherche/, "1-presentation-architecture"],

  // Inventaire
  [/^\/inventaire/, "6-3-production-organisation"],
];

export function getManualSectionForRoute(pathname: string): string | null {
  for (const [re, id] of RAW_MAP) {
    if (re.test(pathname)) return id;
  }
  return null;
}
